import { Quicksand } from "next/font/google";
import { Sidebar } from "./components/Sidebar";

import "./globals.css";
import SessionAuthProvider from "../../context/SessionAuthProvider";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata = {
	title: "SG MascoClinic",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<SessionAuthProvider>
				<body>
					<div className="overflow-y-auto w-full h-full bg-primary-200 flex">
						<Sidebar />
						{children}
					</div>
				</body>
			</SessionAuthProvider>
		</html>
	);
}
